theme: jekyll-theme-minimal
title: Caleb Trimbles Code Portfolio
description: Here you will find the projects worked on by me.
markdown: kramdown
plugins:
  - jekyll-sitemap
permalink: pretty
links:
  - title: About Me
    url: /about.html
  - title: Projects
    url: /projects.html
  - title: Contact
    url: /contact.html
