remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Caleb Trimble's Portfolio
description: Explore my professional journey and projects.

# Add navigation links
links:
  - title: Home
    url: /
  - title: About Me
    url: /about/
  - title: Projects
    url: /project/
  - title: Contact
    url: /contact/
