theme: jekyll-theme-modernist
title: Caleb Trimble's Portfolio
description: Explore my professional journey and projects.

# Add navigation links
links:
  - title: Home
    url: /
  - title: About Me
    url: /about/
  - title: Projects
    url: /project/
  - title: Contact
    url: /contact/
